<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container39XbS3x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container39XbS3x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container39XbS3x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container39XbS3x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container39XbS3x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '39XbS3x',
    'container.build_id' => '78f8839f',
    'container.build_time' => 1575331989,
], __DIR__.\DIRECTORY_SEPARATOR.'Container39XbS3x');
